### ISSUE TITLE
Activate delay after the mpv initialization 

### ISSUE THREAD

**Issue by evansan** [fatihkaan22/mpv-bluetooth-av-delay#1]
It would be great if delay activation works, if new BT audio is detected when video is playing. And when BT audio is disconnected undo the delay.

**Comment by fatihkaan22** [comment]
It's a good idea. The problem is I don't know if either mpv or pulseaudio have some kind of hook to detect audio sink changes. Even though it is not the best way to do this, it can be done by checking current audio device for every 1 second. If you have another idea feel free to share it.

**Comment by evansan** [comment]
There is an official script that checks audio devices actively https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/audio-hotplug-test.lua

**Comment by fatihkaan22** [comment]
I implemented using the script and committed.

**Comment by evansan** [comment]
Thank you, works great.
